[2024-05-30T07:46:44.645+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T07:46:44.657+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_complex.delete_entry manual__2024-05-30T07:46:29.496104+00:00 [queued]>
[2024-05-30T07:46:44.661+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_complex.delete_entry manual__2024-05-30T07:46:29.496104+00:00 [queued]>
[2024-05-30T07:46:44.661+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-30T07:46:44.665+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): delete_entry> on 2024-05-30 07:46:29.496104+00:00
[2024-05-30T07:46:44.670+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3711) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-30T07:46:44.670+0000] {standard_task_runner.py:63} INFO - Started process 3713 to run task
[2024-05-30T07:46:44.670+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_complex', 'delete_entry', 'manual__2024-05-30T07:46:29.496104+00:00', '--job-id', '38', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_complex.py', '--cfg-path', '/tmp/tmpeg50os4v']
[2024-05-30T07:46:44.672+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask delete_entry
[2024-05-30T07:46:44.690+0000] {task_command.py:426} INFO - Running <TaskInstance: example_complex.delete_entry manual__2024-05-30T07:46:29.496104+00:00 [running]> on host fc2d9abb473f
[2024-05-30T07:46:44.719+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_complex' AIRFLOW_CTX_TASK_ID='delete_entry' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T07:46:29.496104+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T07:46:29.496104+00:00'
[2024-05-30T07:46:44.720+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T07:46:44.720+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-30T07:46:44.721+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo delete_entry']
[2024-05-30T07:46:44.726+0000] {subprocess.py:86} INFO - Output:
[2024-05-30T07:46:44.727+0000] {subprocess.py:93} INFO - delete_entry
[2024-05-30T07:46:44.727+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-30T07:46:44.727+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T07:46:44.737+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=example_complex, task_id=delete_entry, run_id=manual__2024-05-30T07:46:29.496104+00:00, execution_date=20240530T074629, start_date=20240530T074644, end_date=20240530T074644
[2024-05-30T07:46:44.763+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-30T07:46:44.770+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-30T07:46:44.771+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
