[2024-05-30T07:46:33.632+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-30T07:46:33.663+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_complex.update_entry manual__2024-05-30T07:46:29.496104+00:00 [queued]>
[2024-05-30T07:46:33.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_complex.update_entry manual__2024-05-30T07:46:29.496104+00:00 [queued]>
[2024-05-30T07:46:33.670+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-30T07:46:33.681+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): update_entry> on 2024-05-30 07:46:29.496104+00:00
[2024-05-30T07:46:33.699+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3581) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-30T07:46:33.708+0000] {standard_task_runner.py:63} INFO - Started process 3598 to run task
[2024-05-30T07:46:33.706+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_complex', 'update_entry', 'manual__2024-05-30T07:46:29.496104+00:00', '--job-id', '9', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_complex.py', '--cfg-path', '/tmp/tmpoal8uwsj']
[2024-05-30T07:46:33.712+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask update_entry
[2024-05-30T07:46:33.749+0000] {task_command.py:426} INFO - Running <TaskInstance: example_complex.update_entry manual__2024-05-30T07:46:29.496104+00:00 [running]> on host fc2d9abb473f
[2024-05-30T07:46:33.798+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_complex' AIRFLOW_CTX_TASK_ID='update_entry' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T07:46:29.496104+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-30T07:46:29.496104+00:00'
[2024-05-30T07:46:33.799+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-30T07:46:33.799+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-30T07:46:33.800+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo update_entry']
[2024-05-30T07:46:33.816+0000] {subprocess.py:86} INFO - Output:
[2024-05-30T07:46:33.818+0000] {subprocess.py:93} INFO - update_entry
[2024-05-30T07:46:33.819+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-30T07:46:33.821+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-30T07:46:33.844+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=example_complex, task_id=update_entry, run_id=manual__2024-05-30T07:46:29.496104+00:00, execution_date=20240530T074629, start_date=20240530T074633, end_date=20240530T074633
[2024-05-30T07:46:33.882+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-30T07:46:33.895+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-30T07:46:33.898+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
